product_list = ['trench_coat',
                'coat',
                'padded_jacket',
                'military',
                'blazer',
                'leather_jacket',
                'fur_jacket',
                'short_sleeve_jacket',
                'long_sleeve_jacket',
                'shirt',
                'blouse',
                'neat',
                'hoodie',
                'sweat_shirt',
                'denim_pants',
                'mini_skirt',
                'skirt',
                'slacks',
                'short_pants',
                'sports_wear',
                'leggings',
                'sports_shoes',
                'sandal',
                'heel',
                'loafers',
                'walker',
                'dress',
                'back_pack',
                'tote_bag',
                'clutch_bag',
                'shoulder_bag',
                'eco_bag']
for i in product_list:
    word = 'CREATE TABLE "index_sentvalue_' + i + '"' + '("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "positive_value" integer unsigned NOT NULL CHECK ("positive_value" >= 0), "neutral_value" integer unsigned NOT NULL CHECK ("neutral_value" >= 0), "negative_value" integer unsigned NOT NULL CHECK ("negative_value" >= 0));'
    print(word)