# Generated by Django 3.1.3 on 2021-08-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FashionScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jan', models.PositiveIntegerField(default=0)),
                ('Feb', models.PositiveIntegerField(default=0)),
                ('Mar', models.PositiveIntegerField(default=0)),
                ('Apr', models.PositiveIntegerField(default=0)),
                ('May', models.PositiveIntegerField(default=0)),
                ('June', models.PositiveIntegerField(default=0)),
                ('July', models.PositiveIntegerField(default=0)),
                ('Aug', models.PositiveIntegerField(default=0)),
                ('Sep', models.PositiveIntegerField(default=0)),
                ('Oct', models.PositiveIntegerField(default=0)),
                ('Nov', models.PositiveIntegerField(default=0)),
                ('Dec', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
