# Generated by Django 3.1.3 on 2021-08-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashionscore',
            name='month_1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fashionscore',
            name='month_2',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fashionscore',
            name='month_3',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
