# Generated by Django 3.1.3 on 2021-08-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20210806_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('value', models.PositiveIntegerField(default=0)),
                ('group', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
