# Generated by Django 3.1.3 on 2021-08-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_sentscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentscore',
            name='negative_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sentscore',
            name='neutral_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sentscore',
            name='positive_value',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
