# Generated by Django 3.1.3 on 2021-08-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20210807_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentscore',
            name='group',
            field=models.CharField(max_length=200),
        ),
    ]
