# Generated by Django 3.1.3 on 2021-08-07 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20210807_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashionscore',
            name='month_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
