# Generated by Django 3.1.3 on 2021-08-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_remove_fashionscore_month_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_score', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
