# Generated by Django 3.1.3 on 2021-08-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_ranking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ranking',
            old_name='social_score',
            new_name='ranking_score',
        ),
        migrations.RemoveField(
            model_name='sentscore',
            name='negative_value',
        ),
        migrations.RemoveField(
            model_name='sentscore',
            name='neutral_value',
        ),
        migrations.RemoveField(
            model_name='sentscore',
            name='positive_value',
        ),
        migrations.AddField(
            model_name='fashionscore',
            name='negative_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fashionscore',
            name='neutral_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fashionscore',
            name='positive_value',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ranking',
            name='ranking_img',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AddField(
            model_name='ranking',
            name='ranking_name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
    ]
