# Generated by Django 3.1.3 on 2021-08-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20210807_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_value', models.PositiveIntegerField(default=0)),
                ('neutral_value', models.PositiveIntegerField(default=0)),
                ('negative_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='fashionscore',
            name='negative_value',
        ),
        migrations.RemoveField(
            model_name='fashionscore',
            name='neutral_value',
        ),
        migrations.RemoveField(
            model_name='fashionscore',
            name='positive_value',
        ),
    ]
