# Generated by Django 3.1.3 on 2021-08-18 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20210818_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='FashionScore_musinsa_shirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jan', models.PositiveIntegerField(default=0)),
                ('Feb', models.PositiveIntegerField(default=0)),
                ('Mar', models.PositiveIntegerField(default=0)),
                ('Apr', models.PositiveIntegerField(default=0)),
                ('May', models.PositiveIntegerField(default=0)),
                ('June', models.PositiveIntegerField(default=0)),
                ('July', models.PositiveIntegerField(default=0)),
                ('Aug', models.PositiveIntegerField(default=0)),
                ('Sep', models.PositiveIntegerField(default=0)),
                ('Oct', models.PositiveIntegerField(default=0)),
                ('Nov', models.PositiveIntegerField(default=0)),
                ('Dec', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FashionScore_ssf_shirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jan', models.PositiveIntegerField(default=0)),
                ('Feb', models.PositiveIntegerField(default=0)),
                ('Mar', models.PositiveIntegerField(default=0)),
                ('Apr', models.PositiveIntegerField(default=0)),
                ('May', models.PositiveIntegerField(default=0)),
                ('June', models.PositiveIntegerField(default=0)),
                ('July', models.PositiveIntegerField(default=0)),
                ('Aug', models.PositiveIntegerField(default=0)),
                ('Sep', models.PositiveIntegerField(default=0)),
                ('Oct', models.PositiveIntegerField(default=0)),
                ('Nov', models.PositiveIntegerField(default=0)),
                ('Dec', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Review_musinsa_shirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review_ssf_shirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SentScore_musinsa_shirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('value', models.PositiveIntegerField(default=0)),
                ('group', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SentScore_ssf_shirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('value', models.PositiveIntegerField(default=0)),
                ('group', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SentValue_musinsa_shirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_value', models.PositiveIntegerField(default=0)),
                ('neutral_value', models.PositiveIntegerField(default=0)),
                ('negative_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SentValue_ssf_shirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_value', models.PositiveIntegerField(default=0)),
                ('neutral_value', models.PositiveIntegerField(default=0)),
                ('negative_value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='shirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jan', models.PositiveIntegerField(default=0)),
                ('Feb', models.PositiveIntegerField(default=0)),
                ('Mar', models.PositiveIntegerField(default=0)),
                ('Apr', models.PositiveIntegerField(default=0)),
                ('May', models.PositiveIntegerField(default=0)),
                ('June', models.PositiveIntegerField(default=0)),
                ('July', models.PositiveIntegerField(default=0)),
                ('Aug', models.PositiveIntegerField(default=0)),
                ('Sep', models.PositiveIntegerField(default=0)),
                ('Oct', models.PositiveIntegerField(default=0)),
                ('Nov', models.PositiveIntegerField(default=0)),
                ('Dec', models.PositiveIntegerField(default=0)),
                ('month_1', models.PositiveIntegerField(default=0)),
                ('month_2', models.PositiveIntegerField(default=0)),
                ('month_3', models.PositiveIntegerField(default=0)),
                ('word', models.CharField(max_length=200)),
                ('value', models.PositiveIntegerField(default=0)),
                ('group', models.CharField(max_length=200)),
                ('positive_value', models.PositiveIntegerField(default=0)),
                ('neutral_value', models.PositiveIntegerField(default=0)),
                ('negative_value', models.PositiveIntegerField(default=0)),
                ('ranking_name', models.CharField(max_length=50)),
                ('ranking_img', models.ImageField(default=0, upload_to='')),
                ('ranking_score', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='musinsa_shirt',
        ),
        migrations.DeleteModel(
            name='ssf_shirt',
        ),
    ]
