# Generated by Django 3.1.3 on 2021-08-18 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_auto_20210818_1442'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SentScore_ssf_shirt',
            new_name='SentScore_shirt',
        ),
        migrations.DeleteModel(
            name='SentScore_musinsa_shirt',
        ),
        migrations.DeleteModel(
            name='SentSocre_shirt',
        ),
        migrations.DeleteModel(
            name='SentValue_musinsa_shirt',
        ),
        migrations.DeleteModel(
            name='SentValue_ssf_shirt',
        ),
    ]
