# Generated by Django 3.1.3 on 2021-08-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_auto_20210818_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking_pants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_name', models.CharField(max_length=50)),
                ('ranking_img', models.ImageField(default=0, upload_to='')),
                ('ranking_score', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Ranking_shirt',
            new_name='Ranking_outer',
        ),
    ]
