# Generated by Django 3.1.3 on 2021-08-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_ranking_accessory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ranking_outer',
        ),
        migrations.AddField(
            model_name='fashionscore_shirt',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
