# Generated by Django 3.1.3 on 2021-08-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_auto_20210818_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='fashionscore_ssf_shirt',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
