# Generated by Django 3.1.3 on 2021-08-18 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0021_fashionscore_ssf_shirt_score'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ranking_shirt',
            new_name='Ranking_outer',
        ),
    ]
