# Generated by Django 3.1.3 on 2021-08-23 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0023_auto_20210821_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review_musinsa_trench_coat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Review_seoulstore_trench_coat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Review_ssf_trench_coat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('date', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='FashionScore_ssf',
            new_name='FashionScore_musinsa_trench_coat',
        ),
        migrations.RenameModel(
            old_name='FashionScore_musinsa',
            new_name='FashionScore_seoulstore_trench_coat',
        ),
        migrations.RenameModel(
            old_name='FashionScore_seoulstore',
            new_name='FashionScore_ssf_trench_coat',
        ),
        migrations.RenameModel(
            old_name='FashionScore',
            new_name='FashionScore_trench_coat',
        ),
        migrations.RenameModel(
            old_name='Ranking_outer',
            new_name='Ranking_trench_coat',
        ),
        migrations.RenameModel(
            old_name='SentScore_shirt',
            new_name='SentScore_trench_coat',
        ),
        migrations.RenameModel(
            old_name='SentValue_shirt',
            new_name='SentValue_trench_coat',
        ),
        migrations.DeleteModel(
            name='Review_musinsa_shirt',
        ),
        migrations.DeleteModel(
            name='Review_seoulstore_shirt',
        ),
        migrations.DeleteModel(
            name='Review_ssf_shirt',
        ),
    ]
