# Generated by Django 3.1.3 on 2021-11-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0025_auto_20210824_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentvalue_fur_jacket',
            name='s',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
